apiVersion: v1
kind: Secret
metadata:
  name: kerkapp-config
type: Opaque
data:
  security.jwt.secret: {{ .Values.env.security.jwt.secret }}
  security.service.username: {{ .Values.env.security.service.username }}
  security.service.password: {{ .Values.env.security.service.password }}