# Shared configs for all microservices connecting to the config server
eureka:
  instance:
    prefer-ip-address: false # Enable to use ip-address instead of hostname
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of Eureka discovery server

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/users/current # The url where the userinfo of the current user can be requested