apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kafka.name" . }}
    helm.sh/chart: {{ template "kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: kafka
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
  - name: kafka
    port: {{ .Values.service.port }}
    {{- if and .Values.service.nodePort (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: kafka
  {{- if .Values.auth.ssl }}
  - name: kafka-ssl
    port: 9093
    targetPort: kafka-ssl
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka
