
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared # Location where the config files need to be
  profiles:
    active: native # Native means local filesystem. For now this will do. In future use a Git Repo or HashiCorp Vaults  
  security:
    user:
      password: kerkapp123 # Password needed to use the config server

server:
  port: 8888